[
  "dameunejemplodejavascript",
  "dimeunejemplodejavascript",
  "mepuedesdecirunejemplodejavascript",
  "dimeunejemplodecodigojavascript",
  "mepuedesdecirunejemplodecodigojavascript",
  "dimeunejemplodejs",
  "dameunejemplodejs",
  "mepuedesdecirunejemplodejs",
  "mepuedesdecirunejemplodecodigojs",
  "dimeuncodedejs",
  "puedesprogramarunejemplodecodigojavascript"
];
